$(".item1").click(function(){
  $("#carouselExampleIndicators").carousel(0);
});
$(".item2").click(function(){
  $("#carouselExampleIndicators").carousel(1);
});
$(".item3").click(function(){
  $("#carouselExampleIndicators").carousel(2);
});
$(".item4").click(function(){
  $("#carouselExampleIndicators").carousel(3);
});